#MySQL Settings
mysql_root_password: "root123"
mysql_db: "wpdb"
mysql_user: "wpuser"
mysql_password: "password123"

#PHP Settings
php_modules: [ 'php', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#HTTP Settings
http_host: "wp.ram-iyer.com"
http_conf: "wp.ram-iyer.com.conf"
http_port: "80"